export const toolslist = [
    {
      id: "1",
      name: "React.js",
      description: "A JavaScript library for building user interfaces.",
      imageUrl: "https://example.com/images/react.png",
      externalUrl: "https://reactjs.org/",
      category: "Framework",
    },
    {
      id: "2",
      name: "Tailwind CSS",
      description: "A utility-first CSS framework for rapidly building custom designs.",
      imageUrl: "https://example.com/images/tailwind.png",
      externalUrl: "https://tailwindcss.com/",
      category: "Framework",
    },
    {
      id: "3",
      name: "PostgreSQL",
      description: "A powerful, open-source object-relational database system.",
      imageUrl: "https://example.com/images/postgresql.png",
      externalUrl: "https://www.postgresql.org/",
      category: "Database",
    },
    {
      id: "4",
      name: "Figma",
      description: "A collaborative interface design tool.",
      imageUrl: "https://example.com/images/figma.png",
      externalUrl: "https://www.figma.com/",
      category: "Design Tool",
    },
    {
      id: "5",
      name: "TypeScript",
      description: "A strongly typed programming language that builds on JavaScript.",
      imageUrl: "https://example.com/images/typescript.png",
      externalUrl: "https://www.typescriptlang.org/",
      category: "Programming Language",
    },
    {
      id: "6",
      name: "Roboto",
      description: "A modern, geometric sans-serif font family.",
      imageUrl: "https://example.com/images/roboto.png",
      externalUrl: "https://fonts.google.com/specimen/Roboto",
      category: "Typography",
    },
    {
      id: "7",
      name: "Next.js",
      description: "A React framework for production-grade applications.",
      imageUrl: "https://example.com/images/nextjs.png",
      externalUrl: "https://nextjs.org/",
      category: "Framework",
    },
    {
      id: "8",
      name: "MongoDB",
      description: "A NoSQL database program that uses JSON-like documents.",
      imageUrl: "https://example.com/images/mongodb.png",
      externalUrl: "https://www.mongodb.com/",
      category: "Database",
    },
    {
      id: "9",
      name: "Sketch",
      description: "A vector graphics editor for interface design.",
      imageUrl: "https://example.com/images/sketch.png",
      externalUrl: "https://www.sketch.com/",
      category: "Design Tool",
    },
    {
      id: "10",
      name: "Open Sans",
      description: "A humanist sans-serif typeface designed for legibility.",
      imageUrl: "https://example.com/images/opensans.png",
      externalUrl: "https://fonts.google.com/specimen/Open+Sans",
      category: "Typography",
    },
    {
      id: "11",
      name: "Angular",
      description: "A platform for building mobile and desktop web applications.",
      imageUrl: "https://example.com/images/angular.png",
      externalUrl: "https://angular.io/",
      category: "Framework",
    },
    {
      id: "12",
      name: "MySQL",
      description: "A popular open-source relational database management system.",
      imageUrl: "https://example.com/images/mysql.png",
      externalUrl: "https://www.mysql.com/",
      category: "Database",
    },
    {
      id: "13",
      name: "Adobe XD",
      description: "A design tool for wireframes, prototypes, and UI/UX designs.",
      imageUrl: "https://example.com/images/adobexd.png",
      externalUrl: "https://www.adobe.com/products/xd.html",
      category: "Design Tool",
    },
    {
      id: "14",
      name: "Lato",
      description: "A sans-serif typeface family designed for clarity and professionalism.",
      imageUrl: "https://example.com/images/lato.png",
      externalUrl: "https://fonts.google.com/specimen/Lato",
      category: "Typography",
    },
    {
      id: "15",
      name: "Vue.js",
      description: "A progressive JavaScript framework for building user interfaces.",
      imageUrl: "https://example.com/images/vue.png",
      externalUrl: "https://vuejs.org/",
      category: "Framework",
    },
    {
      id: "16",
      name: "SQLite",
      description: "A lightweight database engine, embedded into applications.",
      imageUrl: "https://example.com/images/sqlite.png",
      externalUrl: "https://sqlite.org/",
      category: "Database",
    },
    {
      id: "17",
      name: "Canva",
      description: "An online graphic design tool for non-designers.",
      imageUrl: "https://example.com/images/canva.png",
      externalUrl: "https://www.canva.com/",
      category: "Design Tool",
    },
    {
      id: "18",
      name: "Playfair Display",
      description: "A serif typeface suitable for headlines and elegant designs.",
      imageUrl: "https://example.com/images/playfair.png",
      externalUrl: "https://fonts.google.com/specimen/Playfair+Display",
      category: "Typography",
    },
    // Add 32 more objects with similar categories
  ];
  